import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/components/Provider";
import { TaskProvider } from "@/context/TaskContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <Provider>
          <TaskProvider>{children}</TaskProvider>
        </Provider>
      </body>
    </html>
  );
}
